/**
 * =============================================================================
 * THREAD — Sanity CMS pre-build fetch script
 * =============================================================================
 * Run automatically before `vite build` when SANITY_PROJECT_ID is set.
 * Fetches all content from Sanity and writes TypeScript files to
 * src/content/_generated/ so Vite can pick them up via a path alias.
 *
 * If SANITY_PROJECT_ID is not set, the script exits quietly and the build
 * falls back to the hardcoded values in src/content/*.ts — no CMS needed
 * for local development.
 *
 * Usage (normally called via `npm run fetch-content`):
 *   SANITY_PROJECT_ID=xxx SANITY_DATASET=production SANITY_TOKEN=xxx tsx scripts/fetch-content.ts
 * =============================================================================
 */

import { createClient, type SanityClient } from "@sanity/client";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// ─── Config ──────────────────────────────────────────────────────────────────

const projectId = process.env.SANITY_PROJECT_ID;
const dataset = process.env.SANITY_DATASET ?? "production";
const token = process.env.SANITY_TOKEN;
const useDrafts = process.env.SANITY_USE_DRAFTS === "true";

if (!projectId) {
  console.log("[fetch-content] SANITY_PROJECT_ID not set — skipping CMS fetch, using hardcoded content.");
  process.exit(0);
}

const client: SanityClient = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  useCdn: false,
  token,
  perspective: useDrafts ? "previewDrafts" : "published",
});

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outDir = join(__dirname, "..", "src", "content", "_generated");
mkdirSync(outDir, { recursive: true });

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Write a generated TypeScript file with a standard header comment. */
function write(filename: string, content: string) {
  const header = `// AUTO-GENERATED by scripts/fetch-content.ts — do not edit by hand.\n// Edit content in Sanity Studio and rebuild.\n\n`;
  writeFileSync(join(outDir, filename), header + content, "utf8");
  console.log(`[fetch-content] wrote ${filename}`);
}

/** Serialize a JS value to a TypeScript-compatible literal string. */
function serialize(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const inner = "  ".repeat(indent + 1);

  if (value === null || value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => `${inner}${serialize(v, indent + 1)}`).join(",\n");
    return `[\n${items},\n${pad}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${inner}${k}: ${serialize(v, indent + 1)}`);
    if (entries.length === 0) return "{}";
    return `{\n${entries.join(",\n")},\n${pad}}`;
  }

  return String(value);
}

// ─── Fetch helpers ────────────────────────────────────────────────────────────

/** Resolve a Sanity image asset reference to a CDN URL. */
function imageUrl(ref: string | null | undefined): string | undefined {
  if (!ref) return undefined;
  // ref format: image-<id>-<dimensions>-<format>
  const match = ref.match(/^image-([a-f0-9]+)-(\d+x\d+)-(\w+)$/);
  if (!match) return undefined;
  const [, id, dims, fmt] = match;
  return `https://cdn.sanity.io/images/${projectId}/${dataset}/${id}-${dims}.${fmt}`;
}

// ─── site.ts ─────────────────────────────────────────────────────────────────

async function generateSite() {
  const raw = await client.fetch(`*[_type == "siteSettings"][0]`);

  if (!raw) {
    console.warn("[fetch-content] siteSettings document not found — skipping site.ts generation.");
    return;
  }

  const event = {
    name: raw.eventName ?? "THREAD",
    edition: raw.edition ?? "26",
    poweredBy: raw.poweredBy ?? "Powered by Filigran",
    dateLabel: raw.dateLabel ?? "October 15, 2026",
    countdownTo: {
      year: raw.countdownYear ?? 2026,
      month: raw.countdownMonth ?? 10,
      day: raw.countdownDay ?? 15,
      hour: raw.countdownHour ?? 8,
      minute: raw.countdownMinute ?? 30,
    },
    venueShort: raw.venueShort ?? "Les Jardins de Saint-Dominique, Paris",
    admission: raw.admission ?? "Inaugural Event",
    pitch: raw.pitch ?? "",
    credential: raw.credential ?? "",
    credentialEmphasis: raw.credentialEmphasis ?? "",
    contactEmail: raw.contactEmail ?? "events@filigran.io",
  };

  const glance = (raw.glance ?? []).map((g: Record<string, unknown>) => ({
    icon: g.icon,
    title: g.title,
    detail: g.detail,
  }));

  const glanceNote = raw.glanceNote ?? "";

  const venue = {
    kicker: raw.venueKicker ?? "The venue",
    title: raw.venueTitle ?? "Les Jardins de Saint-Dominique",
    description: raw.venueDescription ?? "",
    address: raw.venueAddress ?? "",
    dateAndHours: raw.venueDateAndHours ?? "",
    capacity: raw.venueCapacity ?? "",
    gardenNote: raw.venueGardenNote ?? "",
    landmarks: raw.venueLandmarks ?? "",
    transit: raw.venueTransit ?? "",
    mapsUrl: raw.venueMapsUrl ?? "",
  };

  const register = {
    kicker: raw.registerKicker ?? "Join us",
    title: raw.registerTitle ?? "This is your event.",
    description: raw.registerDescription ?? "",
    primaryButton: raw.registerPrimaryButton ?? "Request your seat",
    secondaryButton: raw.registerSecondaryButton ?? "Propose a session",
    note: raw.registerNote ?? "",
  };

  const footerLinks = {
    filigran: (raw.footerFiligranLinks ?? []).map((l: Record<string, string>) => ({
      label: l.label,
      url: l.url,
    })),
    community: (raw.footerCommunityLinks ?? []).map((l: Record<string, string>) => ({
      label: l.label,
      url: l.url,
    })),
  };

  const footerText = {
    description: raw.footerDescription ?? "",
    filigree: raw.footerFiligree ?? "",
    copyright: `© ${new Date().getFullYear()} Filigran. All rights reserved.`,
    tagline: raw.footerTagline ?? "",
  };

  write(
    "site.ts",
    [
      `export const event = ${serialize(event)} as const;`,
      `export const glance = ${serialize(glance)} as const;`,
      `export const glanceNote = ${serialize(glanceNote)};`,
      `export const venue = ${serialize(venue)} as const;`,
      `export const register = ${serialize(register)} as const;`,
      `export const footerLinks = ${serialize(footerLinks)} as const;`,
      `export const footerText = ${serialize(footerText)} as const;`,
    ].join("\n\n"),
  );
}

// ─── agenda.ts ───────────────────────────────────────────────────────────────

async function generateAgenda() {
  const [settingsRaw, tracksRaw] = await Promise.all([
    client.fetch(`*[_type == "agendaSettings"][0]`),
    client.fetch(`*[_type == "agendaTrack"] | order(order asc)`),
  ]);

  const agendaIntro = {
    kicker: settingsRaw?.kicker ?? "October 15, 2026",
    title: settingsRaw?.title ?? "One day, two tracks, four zones.",
    description: settingsRaw?.description ?? "Draft agenda — sessions and speakers are being finalized.",
  };

  const agendaTracks = (tracksRaw ?? []).map((track: Record<string, unknown>) => ({
    id: (track.trackId as Record<string, string>)?.current ?? "",
    label: track.label ?? "",
    sessions: ((track.sessions as unknown[]) ?? []).map((s: unknown) => {
      const session = s as Record<string, unknown>;
      const result: Record<string, unknown> = {
        time: session.time ?? "",
        title: session.title ?? "",
        locations: session.locations ?? [],
      };
      if (session.description) result.description = session.description;
      if (session.highlight) result.highlight = true;
      if (session.evening) result.evening = true;
      return result;
    }),
  }));

  write(
    "agenda.ts",
    [
      `export type RoomId = "signal" | "community" | "strategy" | "lab" | "simulation" | "garden";`,
      ``,
      `export interface Session {`,
      `  time: string;`,
      `  title: string;`,
      `  description?: string;`,
      `  locations: RoomId[];`,
      `  highlight?: boolean;`,
      `  evening?: boolean;`,
      `}`,
      ``,
      `export interface AgendaTrack {`,
      `  id: string;`,
      `  label: string;`,
      `  sessions: Session[];`,
      `}`,
      ``,
      `export const roomLabels: Record<RoomId, string> = {`,
      `  signal: "Signal Room",`,
      `  community: "Community Zone",`,
      `  strategy: "Strategy Room",`,
      `  lab: "Intelligence Lab",`,
      `  simulation: "Simulation Zone",`,
      `  garden: "Private Garden",`,
      `};`,
      ``,
      `export const agendaIntro = ${serialize(agendaIntro)} as const;`,
      ``,
      `export const agendaTracks: AgendaTrack[] = ${serialize(agendaTracks)};`,
    ].join("\n"),
  );
}

// ─── sections.ts ─────────────────────────────────────────────────────────────

async function generateSections() {
  const raw = await client.fetch(`*[_type == "pageSections"][0]`);

  if (!raw) {
    console.warn("[fetch-content] pageSections document not found — skipping sections.ts generation.");
    return;
  }

  const why = {
    kicker: raw.whyKicker ?? "Why THREAD",
    title: raw.whyTitle ?? "Every investigation starts with one small thing.",
    paragraphs: raw.whyParagraphs ?? [],
    tags: raw.whyTags ?? [],
  };

  const audiences = {
    kicker: raw.audiencesKicker ?? "Two audiences, one thread",
    title: raw.audiencesTitle ?? "Built for the people who do the work — and the people who decide.",
    cards: (raw.audiencesCards ?? []).map((c: Record<string, unknown>) => ({
      name: c.name ?? "",
      tagline: c.tagline ?? "",
      icon: c.icon ?? "shield",
      paragraphs: c.paragraphs ?? [],
    })),
  };

  const zones = {
    kicker: raw.zonesKicker ?? "The experience",
    title: raw.zonesTitle ?? "One venue, five spaces.",
    description: raw.zonesDescription ?? "",
    cards: (raw.zonesCards ?? []).map((c: Record<string, unknown>) => ({
      id: c.id ?? "",
      name: c.name ?? "",
      kind: c.kind ?? "",
      description: c.description ?? "",
      color: c.color ?? "electric",
    })),
  };

  const speakers = {
    kicker: raw.speakersKicker ?? "Voices",
    title: raw.speakersTitle ?? "The people on stage do the work.",
    description: raw.speakersDescription ?? "",
    cards: (raw.speakersCards ?? []).map((c: Record<string, unknown>) => {
      const photoRef = (c.photo as Record<string, unknown>)?.asset as Record<string, string> | undefined;
      const entry: Record<string, unknown> = { name: c.name ?? "", role: c.role ?? "" };
      const url = imageUrl(photoRef?._ref);
      if (url) entry.photoUrl = url;
      return entry;
    }),
    note: raw.speakersNote ?? "Want to lead a session? The agenda is built with the community — reach out at",
  };

  const communityExperiences = (raw.communityExperiences ?? []).map((e: Record<string, unknown>) => ({
    name: e.name ?? "",
    description: e.description ?? "",
  }));

  write(
    "sections.ts",
    [
      `export const why = ${serialize(why)} as const;`,
      `export const audiences = ${serialize(audiences)} as const;`,
      `export const zones = ${serialize(zones)} as const;`,
      `export const speakers = ${serialize(speakers)} as const;`,
      `export const communityExperiences = ${serialize(communityExperiences)} as const;`,
    ].join("\n\n"),
  );
}

// ─── sponsors.ts ─────────────────────────────────────────────────────────────

async function generateSponsors() {
  const [settingsRaw, sponsorsRaw] = await Promise.all([
    client.fetch(`*[_type == "sponsorshipSettings"][0]`),
    client.fetch(`*[_type == "sponsor"] | order(tier asc, name asc)`),
  ]);

  const sponsorship = {
    kicker: settingsRaw?.packagesKicker ?? "Sponsors",
    title: settingsRaw?.packagesTitle ?? "Support the community. Shape the conversation.",
    description: settingsRaw?.packagesDescription ?? "",
    tiers: (settingsRaw?.tiers ?? []).map((t: Record<string, unknown>) => ({
      name: t.name ?? "",
      tagline: t.tagline ?? "",
      perks: t.perks ?? [],
      highlighted: t.highlighted ?? false,
      color: t.color ?? "blue",
    })),
    cta: settingsRaw?.packagesCta ?? "Become a sponsor",
    note: settingsRaw?.packagesNote ?? "",
  };

  const sponsors = {
    show: settingsRaw?.show ?? false,
    kicker: settingsRaw?.showcaseKicker ?? "Our sponsors",
    title: settingsRaw?.showcaseTitle ?? "The organizations making THREAD possible.",
    items: (sponsorsRaw ?? []).map((s: Record<string, unknown>) => {
      const logoRef = (s.logo as Record<string, unknown>)?.asset as Record<string, string> | undefined;
      return {
        name: s.name ?? "",
        logoPath: imageUrl(logoRef?._ref) ?? "",
        url: s.url ?? "",
        tier: s.tier,
      };
    }),
  };

  write(
    "sponsors.ts",
    [
      `export interface SponsorItem {`,
      `  name: string;`,
      `  logoPath: string;`,
      `  url: string;`,
      `  tier?: "Premier" | "Partner" | "Supporter";`,
      `}`,
      ``,
      `export const sponsorship = ${serialize(sponsorship)} as const;`,
      ``,
      `export const sponsors: { show: boolean; kicker: string; title: string; items: SponsorItem[] } = ${serialize(sponsors)};`,
    ].join("\n"),
  );
}

// ─── resources.ts ────────────────────────────────────────────────────────────

async function generateResources() {
  const raw = await client.fetch(`*[_type == "resource"] | order(order asc)`);

  const resources = (raw ?? []).map((r: Record<string, unknown>) => ({
    type: r.type ?? "",
    title: r.title ?? "",
    url: r.url ?? "",
  }));

  write(
    "resources.ts",
    [
      `export interface Resource {`,
      `  type: string;`,
      `  title: string;`,
      `  url: string;`,
      `}`,
      ``,
      `export const resources: Resource[] = ${serialize(resources)};`,
    ].join("\n"),
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────

console.log(`[fetch-content] Fetching from Sanity (project: ${projectId}, dataset: ${dataset}, drafts: ${useDrafts})`);

try {
  await Promise.all([
    generateSite(),
    generateAgenda(),
    generateSections(),
    generateSponsors(),
    generateResources(),
  ]);
  console.log("[fetch-content] Done.");
} catch (err) {
  console.error("[fetch-content] Failed:", err);
  process.exit(1);
}
