/**
 * fetch-content.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Pre-build script: pulls all website content from Sanity CMS and writes
 * TypeScript files to src/content/_generated/.  Those files are then
 * consumed by Vite via the @/content alias (see vite.config.ts).
 *
 * Required environment variables:
 *   SANITY_PROJECT_ID   your Sanity project ID (triggers the fetch)
 *   SANITY_DATASET      dataset name (default: "production")
 *   SANITY_TOKEN        read-only API token (required for private datasets)
 *
 * Run:
 *   npm run fetch-content
 *
 * If SANITY_PROJECT_ID is not set, the script exits cleanly and the build
 * falls back to the hardcoded content in src/content/*.ts.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { createClient } from "@sanity/client";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ─── Config ──────────────────────────────────────────────────────────────────

const projectId = process.env.SANITY_PROJECT_ID;
const dataset = process.env.SANITY_DATASET ?? "production";
const token = process.env.SANITY_TOKEN;

if (!projectId) {
  console.log(
    "ℹ  SANITY_PROJECT_ID is not set — skipping Sanity content fetch.\n" +
      "   The build will use the hardcoded content in src/content/*.ts."
  );
  process.exit(0);
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: "2024-01-01",
  useCdn: false,
});

// ─── Output directory ─────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(__dirname, "../src/content/_generated");
fs.mkdirSync(outDir, { recursive: true });

function write(filename: string, body: string): void {
  const header =
    "// Generated by scripts/fetch-content.ts — do not edit manually.\n\n";
  fs.writeFileSync(path.join(outDir, filename), header + body, "utf-8");
  console.log(`  ✓  src/content/_generated/${filename}`);
}

function s(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

// ─── Generators ──────────────────────────────────────────────────────────────

async function generateSite(): Promise<void> {
  const doc = await client.fetch(`*[_type == "siteSettings"][0]`);
  if (!doc) throw new Error("Sanity: no siteSettings document found.");

  write(
    "site.ts",
    `export const event = ${s(doc.event)} as const;

export const glance = ${s(doc.glance)} as const;

export const glanceNote = ${s(doc.glanceNote)};

export const venue = ${s(doc.venue)} as const;

export const register = ${s(doc.register)} as const;

export const footerLinks = ${s(doc.footerLinks)} as const;

/** Copyright year is always the current year at build time. */
export const footerText = {
  ...${s(doc.footerText)},
  copyright: \`© \${new Date().getFullYear()} Filigran. All rights reserved.\`,
} as const;
`
  );
}

async function generateSections(): Promise<void> {
  const doc = await client.fetch(`*[_type == "pageContent"][0]`);
  if (!doc) throw new Error("Sanity: no pageContent document found.");

  write(
    "sections.ts",
    `export const why = ${s(doc.why)} as const;

export const audiences = ${s(doc.audiences)} as const;

export const zones = ${s(doc.zones)} as const;

export const speakers = ${s(doc.speakers)} as const;

export const communityExperiences = ${s(doc.communityExperiences)} as const;
`
  );
}

async function generateAgenda(): Promise<void> {
  const [intro, tracks] = await Promise.all([
    client.fetch(`*[_type == "siteSettings"][0].agendaIntro`),
    client.fetch(
      `*[_type == "agendaTrack"] | order(order asc) { "id": trackId, label, sessions }`
    ),
  ]);

  if (!intro) throw new Error("Sanity: agendaIntro missing from siteSettings.");
  if (!tracks?.length) throw new Error("Sanity: no agendaTrack documents found.");

  write(
    "agenda.ts",
    `export type RoomId =
  | "signal"
  | "community"
  | "strategy"
  | "lab"
  | "simulation"
  | "garden";

export interface Session {
  time: string;
  title: string;
  description?: string;
  locations: RoomId[];
  highlight?: boolean;
  evening?: boolean;
}

export interface AgendaTrack {
  id: string;
  label: string;
  sessions: Session[];
}

export const roomLabels: Record<RoomId, string> = {
  signal: "Signal Room",
  community: "Community Zone",
  strategy: "Strategy Room",
  lab: "Intelligence Lab",
  simulation: "Simulation Zone",
  garden: "Private Garden",
};

export const agendaIntro = ${s(intro)} as const;

export const agendaTracks: AgendaTrack[] = ${s(tracks)};
`
  );
}

async function generateResources(): Promise<void> {
  const items = await client.fetch(
    `*[_type == "resource"] | order(order asc) { type, title, url }`
  );
  if (!items) throw new Error("Sanity: no resource documents found.");

  write(
    "resources.ts",
    `export interface Resource {
  type: string;
  title: string;
  url: string;
}

export const resources: Resource[] = ${s(items)};
`
  );
}

async function generateSponsors(): Promise<void> {
  const [config, items] = await Promise.all([
    client.fetch(`*[_type == "sponsorshipConfig"][0]`),
    client.fetch(
      `*[_type == "sponsor"] | order(order asc) { name, logoPath, url, tier }`
    ),
  ]);
  if (!config) throw new Error("Sanity: no sponsorshipConfig document found.");

  write(
    "sponsors.ts",
    `export interface SponsorItem {
  name: string;
  logoPath: string;
  url: string;
  tier?: "Premier" | "Partner" | "Supporter";
}

export const sponsorship = ${s(config.sponsorship)} as const;

export const sponsors: {
  show: boolean;
  kicker: string;
  title: string;
  items: SponsorItem[];
} = {
  show: ${s(config.show ?? false)},
  kicker: ${s(config.kicker)},
  title: ${s(config.title)},
  items: ${s(items ?? [])},
};
`
  );
}

// ─── Main ────────────────────────────────────────────────────────────────────

console.log(`\nFetching content from Sanity (project: ${projectId}, dataset: ${dataset})…\n`);

await Promise.all([
  generateSite(),
  generateSections(),
  generateAgenda(),
  generateResources(),
  generateSponsors(),
]);

console.log("\nAll content files generated successfully.\n");
